### ISSUE TITLE
Unauthorized error with retrieving the client configuration; cannot get around the error and stuck with resources

### ISSUE THREAD

**Issue by laffey** [cloudposse/terraform-aws-ec2-client-vpn#87]
### Describe the Bug

You all should remove this from the repository. It doesn't work and needs lots of help. Waste of my time.

I can't even destroy the resources because of an unauthorized error, and I am using privileged aws access, so there is no lack of authorization.

Error: UnauthorizedOperation: You are not authorized to perform this operation....

with module.vpn.data.awsutils_ec2_client_vpn_export_client_config.default[0],
│   on .terraform/modules/vpn/main.tf line 264, in data "awsutils_ec2_client_vpn_export_client_config" "default":
│  264: data "awsutils_ec2_client_vpn_export_client_config" "default" {

### Expected Behavior

Error after all resources created. Now I cannot delete resources.

### Steps to Reproduce

terraform apply.
Test your own code...

**Comment by conzy** [comment]
@laffey Just for you and future travellers. This module uses two providers. The official `aws` provider and a `awsutils` [provider](https://github.com/cloudposse/terraform-provider-awsutils) that Cloudposse have developed. I'm sure they have a good reason for the custom provider, but I guess it does break the principle of least surprise a little. 

Your attitude could be better! You are after all using a _free_ module from _their_ opinionated set of modules for their accelerators. 

Because this module also requires the `awsutils` provider you will also need to configure that provider in your root module if you are providing configuration options to the `aws` provider. 

So you probably have something like:

```hcl
provider "aws" {
  region = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::1111111111:role/some_role"
  }
}

module "this_module" {
  source  = "cloudposse/ec2-client-vpn/aws"
  # removed for brevity 
}
```

And you need to update your config to look something like:

```hcl
provider "aws" {
  region = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::1111111111:role/some_role"
  }
}

provider "awsutils" {
  region = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::1111111111:role/some_role"
  }
}


module "this_module" {
  source  = "cloudposse/ec2-client-vpn/aws"
  # removed for brevity 
}
```

You probably could have figured that out in the time it took to open this salty issue

**Comment by nitrocode** [comment]
Thanks @conzy 

The reason why the additional provider is needed is because the upstream aws provider cannot export the aws client vpn configuration so the cloudposse/awsutils provider is used instead

For reference, there is also an examples directory of how to use each module which contains the defined providers

https://github.com/cloudposse/terraform-aws-ec2-client-vpn/blob/a777f96f754e046100cf8d5fe816575877e8e42d/examples/complete/main.tf#L1-L7

And the auto generated required providers section for each module 

https://github.com/cloudposse/terraform-aws-ec2-client-vpn?tab=readme-ov-file#providers

We can probably go one step further and add the required providers to the versions.tf so it's more obvious when doing an init/plan step
